# Setup
title:               Taem
tagline:             '일단 해보자'
description:         'AI DEVELOPER : Trust ALL'
url:                 http://taemchoi.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taemin Choi
  url:               https://github.com/taemchoi
  email:             never7653@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
